### ISSUE TITLE
AndroidSntpClient UndeliverableException

### ISSUE THREAD

**Issue by gaglileo** [AllanHasegawa/Tempo#3]
I have a lot of crashes in my app remote logs, but I can't reproduce them in local. Any suggestion?
This is the crash report:

> Fatal Exception: io.reactivex.exceptions.UndeliverableException: io.tempo.internal.AndroidSntpClient$InetException: Error getting the host (time.google.com) inet address.
       at io.reactivex.plugins.RxJavaPlugins.onError(SourceFile:367)
       at io.reactivex.internal.operators.single.SingleFromCallable.subscribeActual(SourceFile:50)
       at io.reactivex.Single.subscribe(SourceFile:3310)
       at io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SourceFile:89)
       at io.reactivex.Scheduler$DisposeTask.run(SourceFile:579)
       at io.reactivex.internal.schedulers.ScheduledRunnable.run(SourceFile:66)
       at io.reactivex.internal.schedulers.ScheduledRunnable.call(SourceFile:57)
       at java.util.concurrent.FutureTask.run(FutureTask.java:266)
       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
       at java.lang.Thread.run(Thread.java:764)

> Caused by io.tempo.internal.AndroidSntpClient$InetException: Error getting the host (time.google.com) inet address.
       at io.tempo.internal.AndroidSntpClient.queryHostAddress(SourceFile:55)
       at io.tempo.time_sources.SlackSntpTimeSource$requestTime$1.call(SourceFile:52)
       at io.tempo.time_sources.SlackSntpTimeSource$requestTime$1.call(SourceFile:39)
       at io.reactivex.internal.operators.single.SingleFromCallable.subscribeActual(SourceFile:44)
       at io.reactivex.Single.subscribe(SourceFile:3310)
       at io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SourceFile:89)
       at io.reactivex.Scheduler$DisposeTask.run(SourceFile:579)
       at io.reactivex.internal.schedulers.ScheduledRunnable.run(SourceFile:66)
       at io.reactivex.internal.schedulers.ScheduledRunnable.call(SourceFile:57)
       at java.util.concurrent.FutureTask.run(FutureTask.java:266)
       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
       at java.lang.Thread.run(Thread.java:764)

**Comment by AllanHasegawa** [comment]
Hey, sorry about the delay.

I think I know what the problem is. Will try to debug soon. Thank you for reporting it o/

**Comment by AllanHasegawa** [comment]
Thank you for the report. I identified the issue and a fix is now available. Check version `0.1.2`.
