### ISSUE TITLE
UndeliverableException

### ISSUE THREAD

**Issue by slipdef** [AllanHasegawa/Tempo#6]
Looks like some error inside Tempo to suddenly crashes our app in production.

ErrnoException: sendto failed: EPERM (Operation not permitted)
    at libcore.io.Linux.sendtoBytes(Linux.java)
    at libcore.io.Linux.sendto(Linux.java:227)
    at libcore.io.BlockGuardOs.sendto(BlockGuardOs.java:307)
    at libcore.io.IoBridge.sendto(IoBridge.java:542)
    at java.net.PlainDatagramSocketImpl.send(PlainDatagramSocketImpl.java:125)
...
(17 additional frame(s) were not displayed)

IOException: sendto failed: EPERM (Operation not permitted)
    at libcore.io.IoBridge.maybeThrowAfterSendto(IoBridge.java:576)
    at libcore.io.IoBridge.sendto(IoBridge.java:544)
    at java.net.PlainDatagramSocketImpl.send(PlainDatagramSocketImpl.java:125)
    at java.net.DatagramSocket.send(DatagramSocket.java:723)
    at io.tempo.internal.AndroidSntpClient$requestTime$2.invoke(AndroidSntpClient.kt:89)
...
(15 additional frame(s) were not displayed)

AllRequestsFailure: All NTP requests failed: [Error transmitting request/response; Error transmitting request/response; Error transmitting request/response; Error transmitting request/response; Error transmitting request/response]
    at io.tempo.time_sources.SlackSntpTimeSource$requestTime$3.apply(SlackSntpTimeSource.kt:92)
    at io.tempo.time_sources.SlackSntpTimeSource$requestTime$3.apply(SlackSntpTimeSource.kt:40)
    at io.reactivex.internal.operators.single.SingleMap$MapSingleObserver.onSuccess(SingleMap.java:57)
    at io.reactivex.internal.operators.single.SingleFlatMap$SingleFlatMapCallback$FlatMapSingleObserver.onSuccess(SingleFlatMap.java:111)
    at io.reactivex.internal.operators.single.SingleZipArray$ZipCoordinator.innerSuccess(SingleZipArray.java:119)
...
(11 additional frame(s) were not displayed)

UndeliverableException: The exception could not be delivered to the consumer because it has already canceled/disposed the flow or the exception has nowhere to go to begin with. Further reading: https://github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0#error-handling | io.tempo.time_sources.SlackSntpTimeSource$AllRequestsFailure: All NTP requests failed: [Error transmitting request/response; Error transmitting request/response; Error transmitting request/response; Error transmitting request/response; Error transmitting request/response]
    at io.reactivex.plugins.RxJavaPlugins.onError(RxJavaPlugins.java:367)
    at io.reactivex.internal.operators.single.SingleTimeout$TimeoutMainObserver.onError(SingleTimeout.java:152)
    at io.reactivex.internal.operators.single.SingleMap$MapSingleObserver.onError(SingleMap.java:69)
    at io.reactivex.internal.operators.single.SingleMap$MapSingleObserver.onError(SingleMap.java:69)
    at io.reactivex.internal.operators.single.SingleMap$MapSingleObserver.onSuccess(SingleMap.java:60)
...
(13 additional frame(s) were not displayed)

The exception could not be delivered to the consumer because it has already canceled/disposed the flow or the exception has nowhere to go to begin with. Further reading: https://github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0#error-handling | io.tempo.time_sources.SlackSntpTimeSource$AllRequestsFailure: All NTP requests failed: [Error transmitting request/response; Error transmitting request/response; Error transmitting request/response; Error transmitting request/response; Error transmitting request/response]

**Comment by AllanHasegawa** [comment]
I do recommend you to follow the guide on the link: 
https://github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0#error-handling

The `zip` operator can be troublesome and can cause this issue. This happens when one of the streams throws an exception while the other one still running during a `zip` operation. I don't think there's much I could do to fix it. So it's up to the application to handle this type of error. In this case, it's safe to ignore those undelivered exceptions.
